/**
 * @myflowpl/api-server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseError { 
    message: string;
    statusCode: number;
    /**
     * List of validation errors (optional)
     */
    errors?: Array<string>;
}

