/**
 * @myflowpl/api-server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Photo } from './photo';


export interface PhotoCreateResponseDto { 
    photo: Photo;
}

