/**
 * @myflowpl/api-server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Song } from './song';


export interface SongsResponseDto { 
    page: number;
    pageSize: number;
    length: number;
    data: Array<Song>;
}

