/**
 * @myflowpl/api-server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Location } from './location';


export interface User { 
    id?: number;
    name?: string;
    email?: string;
    photo?: string;
    role?: Role;
    location?: Location;
}
export namespace User {
}


