/**
 * Mój Projekt w Nest
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthLoginDto { 
    email: string;
    password: string;
}

