/**
 * Mój Projekt w Nest
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface AuthLoginResponse { 
    token: string;
    user: User;
}

