export * from './artists.api';
import { ArtistsApi } from './artists.api';
export * from './authentication.api';
import { AuthenticationApi } from './authentication.api';
export * from './photos.api';
import { PhotosApi } from './photos.api';
export * from './quotes.api';
import { QuotesApi } from './quotes.api';
export * from './songs.api';
import { SongsApi } from './songs.api';
export const APIS = [ArtistsApi, AuthenticationApi, PhotosApi, QuotesApi, SongsApi];
